// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_GameUpgrade","status":true,"description":"Enables more customization over the core mechanics of one's game while also providing additional functions for future plugins.","parameters":{"Game Window":"====================================","Game Reconstruction (1.5.X & below)":"true","Game Resolution":"{\"Width\":\"1280\",\"Height\":\"720\"}","Screen Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Minimum Resolution":"{\"Width\":\"408\",\"Height\":\"312\"}","Maximum Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Window Title":"","Allow Resize":"true","Initial Fullscreen":"false","Show Frame":"true","Always on Top":"false","Core Defaults":"====================================","Audio Master Volume":"100","Video Master Volume":"100","Image Cache Limit":"30","Decrypter Ignore List":"[\"system/Window.png\"]","JsonEx Max Depth":"100","Retry Intervals":"[\"500\",\"1000\",\"3000\"]","HTML Settings":"====================================","Background Color":"#000000","Image Rendering":"auto","PIXI Settings":"====================================","Garbage Collection Mode":"Automatic","Round Pixels":"false","Scale Mode":"Nearest","Wrap Mode":"Clamp"}},
{"name":"SciFi_Core","status":true,"description":"SciFi Core v0.1.0","parameters":{}},
{"name":"SciFi_UICore","status":true,"description":"SciFi UI Core v0.1.0","parameters":{}},
{"name":"SciFi_MenuUI","status":true,"description":"","parameters":{}},
{"name":"SciFi_ItemInstance","status":true,"description":"SciFi Item Instance System v0.1.0","parameters":{}},
{"name":"SciFi_EquipmentData","status":true,"description":"SciFi Equipment Data v0.3.1","parameters":{}},
{"name":"SciFi_BattleCore","status":true,"description":"SciFi Battle Core v0.3.1","parameters":{}},
{"name":"SciFi_Durability","status":true,"description":"SciFi Durability System v0.2.0","parameters":{}},
{"name":"SciFi_Shield","status":true,"description":"SciFi Shield System v0.7.0","parameters":{"Shielded State ID":"11"}},
{"name":"SciFi_Armor","status":true,"description":"SciFi Armor System v0.2.1","parameters":{}},
{"name":"SciFi_ArmorPiercing","status":true,"description":"SciFi Armor Piercing System v0.1.1","parameters":{}},
{"name":"SciFi_DamageData","status":true,"description":"SciFi Damage Data v0.2.0","parameters":{}},
{"name":"SciFi_ItemUI","status":true,"description":"SciFi Item UI v0.1.0","parameters":{}},
{"name":"SciFi_EquipUI","status":true,"description":"SciFi Equip UI v0.3.0","parameters":{}},
{"name":"SciFi_StatusUI","status":true,"description":"[v1.5] Custom HD Status UI. Panel grouping, dynamic box height, scroll indicators.","parameters":{"--- Layout ---":"","Column Ratios":"30,40,30","Default Portrait":"Actor1_1","--- Font Sizes ---":"","Header Font Size":"28","Content Font Size":"22","Bio Font Size":"20"}},
{"name":"SciFi_SkillUI","status":true,"description":"SciFi Skill UI v0.1.0","parameters":{}},
{"name":"SciFi_ShopUI","status":true,"description":"SciFi Shop UI v0.1.0","parameters":{}},
{"name":"Galv_QuestLog","status":true,"description":"(v.1.3) A system to track quests/sidequests in your RPG.","parameters":{"File":"Quests","Folder":"data","Separator Character":",","- OPTIONS -":"","Font Size":"22","Categories":"Main Quests|#ffcc66,Side Quests|#ffff99,Crafting Quests|#ccccff","-- ICONS --":"","Not Complete Icon":"163","Complete Icon":"164","Failed Icon":"162","Tracked Quest Icon":"88","-- VOCAB --":"","Quest Command":"Quest Log","Active Cmd Txt":"Active","Completed Cmd Txt":"Complete","Failed Cmd Txt":"Failed","Desc Txt":"Details","Objectives Txt":"Objectives","Difficulty Txt":"Level","No Tracked Quest":"No Quest Selected","-- EXTRA --":"","Pop XY":"20,20","Pop Time":"130","Pop New Quest":"New Quest:","Pop Complete Quest":"Quest Completed:","Pop Fail Quest":"Quest Failed:","Pop New Objective":"New Objective:","Pop Complete Objective":"Objective Completed:","Pop Fail Objective":"Objective Failed:"}},
{"name":"SciFi_QuestUI","status":true,"description":"SciFi Quest UI v0.1.0","parameters":{}},
{"name":"SciFi_SaveUI","status":true,"description":"SciFi Save/Load UI v0.1.0","parameters":{}},
{"name":"SciFi_MessageUI","status":true,"description":"SciFi Message UI v0.2.0","parameters":{"--- Layout ---":"","Textbox Height":"180","Name Bar Height":"45","Portrait Width":"370","Portrait Height":"540","--- Styling ---":"","Bubble Background Color":"rgba(44, 27, 32, 0.95)","Bubble Border Color":"#8B857C","Name Bar Background Color":"#2c1b20","Name Bar Border Color":"#8B857C","Text Color":"#fff9df","Name Text Color":"#fff9df","Bubble Padding X":"16","Bubble Padding Y":"12","--- Portrait ---":"","Portrait Offset X":"0.5","Portrait Offset Y":"0.5"}},
{"name":"UT_OpenTypePixelFont","status":true,"description":"Draw true type fonts using opentype.js -- this is the passive version, no need to setup.","parameters":{}},
{"name":"Status Menu","status":false,"description":"SciFi Stats","parameters":{}},
{"name":"J_Critical_Multiplier","status":true,"description":"Changes the Critical Multiplier.","parameters":{"Multiplier":"1.5"}},
{"name":"OrangeOverlay","status":true,"description":"v1.1.4 - Adds overlay images to the map <OrangeOverlay>","parameters":{"Organized Folders":"false","Parallax Layer Filename":"par","Ground Layer Filename":"ground","Light Layer Filename":"light","Shadow Layer Filename":"shadow","Light Opacity":"185","Quick Start":"true","Bush Region ID":"7","Fog Switch ID":"1","Light Switch ID":"2","Parallax Switch ID":"3","Shadow Switch ID":"4"}},
{"name":"GALV_MessageBusts","status":false,"description":"(v.2.8) Displays a bust image instead of selected face image","parameters":{"Bust Priority":"1","Bust Position":"1","Text X Offset":"390","Fade Out Speed":"32","Filename Append":""}}
];
